remote_theme: qwtel/hydejack 

description: Creative + Practical Bootstrap Examples 

accent_image: /assets/sidebar-img.jpg
accent_color: '#000067'

author:
  social:
    twitter: maxshal_
    github: https://github.com/MaxShalom/BootstrapX
